### ISSUE TITLE
yarn migrate failing

### ISSUE THREAD

**Issue by CodyBontecou** [zzacong/spritzee-pusher-nextjs#1]
Running yarn migrate gives me the following error: 

```
P1000: Authentication failed against database server at `containers-us-west-81.railway.app`, the provided database credentials for `postgres` are not valid.
```

**Comment by zzacong** [comment]
Hi @CodyBontecou , the `DATABASE_URL` in `.env-example` was checked in by mistake. I would suggest you to set up your own postgres database.

**Comment by CodyBontecou** [comment]
Aha okay, that's what I ended up doing then I ran `npx prisma migrate dev --name init` and was good to go.
